# Generated by Django 3.0.1 on 2021-05-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210512_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthdate',
        ),
    ]
