# Generated by Django 3.0.1 on 2021-05-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
    ]
